// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc364.subsystems;

import org.usfirst.frc364.Robot;
import org.usfirst.frc364.RobotMap;
import org.usfirst.frc364.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

public class liftSystem extends PIDSubsystem {
	
    public SpeedController liftMotor = RobotMap.liftSystemliftMotor;
    AnalogInput liftPot = RobotMap.liftSystemliftPot;
    
    public liftSystem() {
        super("liftSystem", 1, 0.0, 0.1);
        setAbsoluteTolerance(0);
        getPIDController().setContinuous(false);
        LiveWindow.addActuator("liftSystem", "PIDSubsystem Controller", getPIDController());
        getPIDController().setOutputRange(-1.0, 0.5);
        setSetpoint(2);
    }
    	
    public void manualControl() {
    	setSetpoint(Robot.oi.controller.getRawAxis(3) + liftPot.getVoltage());
    }
    
    public void setDropSetpoint() {
    	setSetpoint(3.19);
    }
    
    public void setLiftSetpoint() {
    	setSetpoint(2.0);
    }
    
    public void setTransportSetpoint() {
    	setSetpoint(2.9);
    }
    
    public void initDefaultCommand() {
    	setDefaultCommand(new setPointControl());
    }
    
    protected double returnPIDInput() {
        return liftPot.getAverageVoltage();
    }
    
    protected void usePIDOutput(double output) {
    	double isSetpointTransport = getSetpoint();
    	if(isSetpointTransport == 2.9) {
    		liftMotor.pidWrite(-output * 3);
    	}
    	else {
    		liftMotor.pidWrite(-output);
    	}
    }
}
