// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc364.subsystems;

import org.usfirst.frc364.RobotMap;
import org.usfirst.frc364.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;

public class shiftSystem extends Subsystem {
	
    public DoubleSolenoid shiftPiston = RobotMap.shiftSystemshiftPiston;

    public void initDefaultCommand() {
        setDefaultCommand(new shiftControl());
    }
}

