// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc364.commands;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc364.Robot;

public class  armControl extends Command {

    public armControl() {
    	requires(Robot.armSystem);
    }

    protected void initialize() {}

    protected void execute() {
    	
    	if(Robot.liftSystem.getPosition() > 2.2) {
    		Robot.armSystem.open();
    	}
    	else {
    		
    		if(Robot.oi.closeArms.get() == true) {
    			Robot.armSystem.close();
    		}
    	
    		if(Robot.oi.openArms.get() == true) {
    			Robot.armSystem.open();
    		}
    	
    		else {
    			Robot.armSystem.off();
    		}
    	}
    }

    protected boolean isFinished() {
        return false;
    }

    protected void end() {
    	end();
    }
    
    protected void interrupted() {}
    
}
