// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc364.commands;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc364.Robot;

/**
 *
 */
public class  shiftControl extends Command {

    public shiftControl() {
    	requires(Robot.shiftSystem);
    }
    
    protected void initialize() {
    }

    protected void execute() {
    	if(Robot.oi.closeArms.get() == true) {
    		Robot.shiftSystem.shiftPiston.set(DoubleSolenoid.Value.kForward);
    	}
    	if(Robot.oi.openArms.get() == true){
    		Robot.shiftSystem.shiftPiston.set(DoubleSolenoid.Value.kReverse);
    	}
    	else{
    		Robot.shiftSystem.shiftPiston.set(DoubleSolenoid.Value.kOff);
    	}
    }

    protected boolean isFinished() {
        return false;
    }

    protected void end() {
    	end();
    }

    protected void interrupted() {
    }
}
