// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc364.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc364.Robot;

public class  shiftControl extends Command {

    public shiftControl() {
    	requires(Robot.shiftSystem);
    	setTimeout(0.1);
    }
    
    protected void initialize() {}

    protected void execute() {
    	
    	if(Robot.oi.shiftHigh.get() == true) {
    		Robot.shiftSystem.shiftHigh();
    	}
    	
    	if(Robot.oi.shiftLow.get() == true) {
    		Robot.shiftSystem.shiftLow();
    	}
    }

    protected boolean isFinished() {
        return isTimedOut();
    }

    protected void end() {
    	Robot.shiftSystem.shiftNothing();
    }

    protected void interrupted() {
    	end();
    }
    
}
